Change ERLANG_VERSION to VERSION
For consistent invacation from `travis-nightly-builder`

diff --git a/bin/archive b/bin/archive
--- a/bin/archive
+++ b/bin/archive
@@ -2,8 +2,8 @@
 
 set -o errexit
 
-[[ ${ERLANG_VERSION} ]] || {
-  echo 'Missing $ERLANG_VERSION' >&2
+[[ ${VERSION} ]] || {
+  echo 'Missing $VERSION' >&2
   exit 1
 }
 
@@ -13,13 +13,13 @@ set -o errexit
 }
 
 tar -C "${HOME}/otp" -cjf \
-  "${TARGET_DIR}/erlang-${ERLANG_VERSION}-nonroot.tar.bz2" \
-  "${ERLANG_VERSION}"
+  "${TARGET_DIR}/erlang-${VERSION}-nonroot.tar.bz2" \
+  "${VERSION}"
 
-echo "Created ${TARGET_DIR}/erlang-${ERLANG_VERSION}-nonroot.tar.bz2"
+echo "Created ${TARGET_DIR}/erlang-${VERSION}-nonroot.tar.bz2"
 
 tar -C / -cjf \
-  "${TARGET_DIR}/erlang-${ERLANG_VERSION}.tar.bz2" \
-  "${HOME}/otp/${ERLANG_VERSION}"
+  "${TARGET_DIR}/erlang-${VERSION}.tar.bz2" \
+  "${HOME}/otp/${VERSION}"
 
-echo "Created ${TARGET_DIR}/erlang-${ERLANG_VERSION}.tar.bz2"
+echo "Created ${TARGET_DIR}/erlang-${VERSION}.tar.bz2"
diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,17 +2,17 @@
 
 set -o errexit
 
-[[ ${ERLANG_VERSION} ]] || {
-  echo 'Missing $ERLANG_VERSION' >&2
+[[ ${VERSION} ]] || {
+  echo 'Missing $VERSION' >&2
   exit 1
 }
 
 if [[ -f ~/.kerl/otp_builds ]] ; then
-  sed -i "/^${ERLANG_VERSION}/d" ~/.kerl/otp_builds
+  sed -i "/^${VERSION}/d" ~/.kerl/otp_builds
 fi
 
 sudo curl -o `which kerl` https://raw.githubusercontent.com/kerl/kerl/master/kerl
 
 bash -x kerl update releases
-kerl build "${ERLANG_VERSION}" "${ERLANG_VERSION}"
-kerl install "${ERLANG_VERSION}" "${HOME}/otp/${ERLANG_VERSION}"
+kerl build "${VERSION}" "${VERSION}"
+kerl install "${VERSION}" "${HOME}/otp/${VERSION}"
